[modpacks]
   comment = Solte os .jar aqui: modpacks/<Perfil>/mods/
   path = /srv/umucraft/staging/profiles
   valid users = SAMBA_USER_PLACEHOLDER
   writable = yes
   browsable = yes
   create mask = 0664
   directory mask = 0775
   force user = SAMBA_USER_PLACEHOLDER

[umucraft-public]
   comment = manifest.json e mapas publicados (o que fica aqui e servido publicamente)
   path = /srv/umucraft/www
   valid users = SAMBA_USER_PLACEHOLDER
   writable = yes
   browsable = yes
   create mask = 0664
   directory mask = 0775
   force user = SAMBA_USER_PLACEHOLDER
